Repository IBM/ibm-garage-tekton-tasks, pull requests merged in 2020-09, with the labels that each got.

#38 Trivy scan task and pipeline changes
  pipelines/appmod-liberty-pipeline.yaml
  pipelines/golang-pipeline-edge.yaml
  pipelines/golang-pipeline.yaml
  pipelines/java-gradle-pipeline.yaml
  pipelines/java-maven-pipeline.yaml
  pipelines/nodejs-pipeline.yaml
  tasks/0-setup.yaml
  tasks/3-img-scan-ibm.yaml
  tasks/3-img-scan-trivy.yaml
Labels: feature, minor

#39 Removes unneeded package.json
  package-lock.json
  package.json
Labels: chore, patch

#41 PERFORM_SCAN check at scan-image step as well
  tasks/3-img-scan-trivy.yaml
Labels: bug, patch
